# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.

# version numbers
jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="f8918c1f-b532-437f-a993-00bb68dc77b8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  -bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту lester_g@inbox.ru если сборка упала
notifications:
  email:
    recipients:
      -lester_g@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always


